[package]
name = "ai"
version = "0.2.2"
edition = "2024"
description = "AI engine abstraction for Lumen"

[dependencies]
models = { workspace = true }
anyhow = { workspace = true }
base64 = "0.23"
futures-core = "0.3"
log = { workspace = true }
reqwest = { workspace = true, features = ["json", "stream", "default-tls"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tiktoken-rs = "0.12"
tokio = { workspace = true, features = ["sync"] }
