[package]
name = "services"
version = "0.2.1"
edition = "2024"

[dependencies]
models = { workspace = true }
database = { workspace = true }
parser = { workspace = true }
anyhow = { workspace = true }
serde_json = { workspace = true }
log = { workspace = true }
serde = { workspace = true, features = ["derive"] }
reqwest = { workspace = true, features = ["json", "stream", "default-tls"] }
phf = { version = "0.13.1", features = ["macros"] }
chrono = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true, features = ["serde", "v4"] }
notify = "8.2.0"
sha2 = { workspace = true }
file = { workspace = true }
unicode-normalization = { workspace = true }
translate = { workspace = true }
i18n = { workspace = true }
directories = "6"
mupdf = "0.8.0"
mupdf-sys = "0.8.0"
image = "0.25"
arboard = "3"
smallvec = "1.13"
