use gpui::SharedString;
use gpui_component::IconNamed;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IconName {
    // ── 通用图标 ──
    File,
    FileSolid,
    Attachment,
    Trash,
    Settings,
    Add,
    Clear,
    Edit,
    Folder,
    Globe,
    Cloud,
    Puzzle,
    Info,
    FolderSelect,
    ArrowUpDown,
    Minimize,
    Maximize,
    Restore,
    Close,
    Copy,
    Check,
    FolderOpen,
    BookOpen,
    Home,
    Plus,
    Inbox,
    ChevronDown,
    ChevronRight,
    ChevronLeft,
    LoaderCircle,
    CircleX,
    TriangleAlert,
    Undo,
    Bell,
    Star,
    GitHub,
    // ── PDF / 编辑器专有 ──
    ZoomIn,
    ZoomOut,
    Sidebar,
    Search,
    Outline,
    Annotations,
    Translate,
    RotateCw,
    Square,
    FitWidth,
    PanelRight,
    FileText,
    Pages,
    FastForward,
    Pin,
    MessageSquare,
    Download,
}

impl IconNamed for IconName {
    fn path(self) -> SharedString {
        match self {
            // Lumen 自有图标（assets/icons/）
            Self::FileSolid => "icons/file_solid.svg".into(),
            Self::Attachment => "icons/attachment.svg".into(),
            Self::Trash => "icons/trash.svg".into(),
            Self::Add => "icons/add.svg".into(),
            Self::Edit => "icons/edit.svg".into(),
            Self::Cloud => "icons/cloud.svg".into(),
            Self::Puzzle => "icons/puzzle.svg".into(),
            Self::Info => "icons/info.svg".into(),
            Self::FolderSelect => "icons/folder_select.svg".into(),
            Self::ArrowUpDown => "icons/arrow_up_down.svg".into(),
            Self::Restore => "icons/restore.svg".into(),
            Self::Home => "icons/home.svg".into(),
            Self::Settings => "icons/settings.svg".into(),
            Self::Globe => "icons/globe.svg".into(),
            Self::Copy => "icons/copy.svg".into(),
            Self::Check => "icons/check.svg".into(),
            Self::Plus => "icons/plus.svg".into(),
            Self::Inbox => "icons/inbox.svg".into(),
            Self::Undo => "icons/undo.svg".into(),
            Self::Bell => "icons/bell.svg".into(),
            Self::Star => "icons/star.svg".into(),
            Self::Folder => "icons/folder.svg".into(),
            Self::Close => "icons/close.svg".into(),
            Self::GitHub => "icons/github.svg".into(),
            Self::Sidebar => "icons/sidebar.svg".into(),
            Self::Search => "icons/search.svg".into(),
            Self::RotateCw => "icons/rotate_cw.svg".into(),
            Self::Square => "icons/square_dashed.svg".into(),
            Self::FitWidth => "icons/arrows_horizontal.svg".into(),
            Self::PanelRight => "icons/panel_right.svg".into(),
            Self::FileText => "icons/note.svg".into(),
            Self::Pages => "icons/layout_grid.svg".into(),
            Self::FastForward => "icons/fast_forward.svg".into(),
            Self::Pin => "icons/pip.svg".into(),
            Self::MessageSquare => "icons/message_square.svg".into(),
            Self::Download => "icons/download.svg".into(),
            // Lumen 自有（下划线命名）
            Self::FolderOpen => "icons/folder_open.svg".into(),
            Self::ChevronDown => "icons/chevron_down.svg".into(),
            Self::ChevronRight => "icons/chevron_right.svg".into(),
            Self::ChevronLeft => "icons/chevron_left.svg".into(),
            Self::Clear => "icons/circle-x.svg".into(),
            Self::Outline => "icons/list_tree.svg".into(),
            Self::Annotations => "icons/edit.svg".into(),
            Self::Translate => "icons/globe.svg".into(),
            Self::ZoomIn => "icons/plus.svg".into(),
            Self::ZoomOut => "icons/minus.svg".into(),
            // gpui-component 图标（通过依赖加载）
            Self::File => "icons/file.svg".into(),
            Self::BookOpen => "icons/book-open.svg".into(),
            Self::Minimize => "icons/minimize.svg".into(),
            Self::Maximize => "icons/maximize.svg".into(),
            Self::CircleX => "icons/circle-x.svg".into(),
            Self::LoaderCircle => "icons/loader-circle.svg".into(),
            Self::TriangleAlert => "icons/triangle-alert.svg".into(),
        }
    }
}
