[package]
name = "parser"
version = "0.2.2"
edition = "2024"

[dependencies]
models = { workspace = true }
database = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
log = { workspace = true }
quick-xml = { workspace = true, features = ["serialize"] }
regex = "1.12.2"
reqwest = { workspace = true, features = ["json", "stream", "default-tls"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
urlencoding = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
biblatex = "0.12.0"
